services:
  - type: web
    name: aquariumdayo
    env: static
    branch: main
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
